### ISSUE TITLE
setting CATALINA_OPTS but doesn't get picked up

### ISSUE THREAD

**Issue by milosonator** [cptactionhank/docker-atlassian-confluence#10]
Hi there,

im having trouble changing the memory usage of confluence, in your description you say to edit the CATALINA_OPTS environment variable. I do this (using docker-compose) (and with docker exec <name> printenv I see the environment variable is set correctly) but the variable is not getting picked up by the startup scripts.. what can I do?

**Comment by cptactionhank** [comment]
Can you provide an example of your docker-compose file?

**Comment by milosonator** [comment]
Like this:

confluence:
  restart: always
  build: ./confluence
  expose:
    - "8090:8090"
  links:
    - postgres
  environment:
    CATALINA_OPTS: "-Xms256m -Xmx512m"

Dockerfile just copies a server.xml nothing else.

**Comment by cptactionhank** [comment]
Hi,

I have just run a setup with the following docker-compose.ml

```
confluence:
  image: cptactionhank/atlassian-confluence
  # command: sleep 55
  environment:
    CATALINA_OPTS: -Xms64m -Xmx768m -Datlassian.plugins.enable.wait=300
  ports:
    - "0.0.0.0:8090:8090"
  expose:
    - 8090
```

and it seems to be working, I have verified this by looking in the url `<..>/admin/systeminfo.action`

Key | Value
------------ | -------------
Java Runtime Arguments | -Djava.util.logging.config.file=/opt/atlassian/confluence/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -XX:-UseAESIntrinsics -Xms1024m -Xmx1024m -XX:+UseG1GC -Djava.awt.headless=true -Xloggc:/opt/atlassian/confluence/logs/gc-2015-08-29_23-08-39.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -XX:-PrintGCDetails -XX:+PrintGCTimeStamps -XX:-PrintTenuringDistribution -Xms64m -Xmx768m -Datlassian.plugins.enable.wait=300 -Djava.endorsed.dirs=/opt/atlassian/confluence/endorsed -Dcatalina.base=/opt/atlassian/confluence -Dcatalina.home=/opt/atlassian/confluence -Djava.io.tmpdir=/opt/atlassian/confluence/temp
Maximum Heap Size | 768 MB
