### ISSUE TITLE
Problem with ProxySupport 

### ISSUE THREAD

**Issue by SITondorf** [cptactionhank/docker-atlassian-confluence#20]
Hello,

tried running confluence behind nginx, but environment-variables don't have any influence on server.xml

docker-compose.yml
```
version: "2"

services:
 database:
  image: postgres:9.3
  restart: always
  ports:
   - "15432:5432"
  environment:
    - POSTGRES_PASSWORD=passwordXXX
    - DB_NAME=confluence
  volumes:
    - /data/docker/pgsql:/var/lib/postgresql/data:Z

 confluence:
  image: cptactionhank/atlassian-confluence:latest
  restart: always
  depends_on:
   - database
  ports:
   - 8090:8090
  environment:
   - X_PROXY_NAME=confluence-gl-gf.local.domain
   - X_PROXY_PORT=443
   - X_PROXY_SECURE=true
   - X_PROXY_SCHEME=https
  volumes:
   - /data/docker/conf:/var/atlassian/confluence:Z
```

/opt/atlassian/confluence/conf/server.xml
```
    <Connector port="8090" connectionTimeout="20000" redirectPort="8443" maxThreads="200" minSpareThreads="10" enableLookups="false" acceptCount="10" URIEncoding="UTF-8" protocol="org.apache.coyote.http11.Http11NioProtocol"/>
```

I always have to change server.xml manually:
```
xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "proxyName" --value "confluence-gl-gf.local.domain" "/opt/atlassian/confluence/conf/server.xml"
xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "proxyPort" --value "443" "/opt/atlassian/confluence/conf/server.xml"
xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "scheme" --value "https" "/opt/atlassian/confluence/conf/server.xml"
xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "secure" --value "true" "/opt/atlassian/confluence/conf/server.xml"
```
After that everything works fine until the container is recreated. But the enviroment variables X_PROXY_.. are never used.

Regards

Markus
