### ISSUE TITLE
5.6.x containers on Docker Hub fail on start

### ISSUE THREAD

**Issue by tilmanpotthof** [cptactionhank/docker-atlassian-confluence#32]
I use the containers for all confluence version and they work all perfect except 5.6.x (I tested 5.6.6 and 5.6.5).

I use docker-compose for my setup and the logs print the following errors

```
confluence_5.6.6_postgres_9.5.2 | Error: Could not create the Java Virtual Machine.
confluence_5.6.6_postgres_9.5.2 | Error: A fatal exception has occurred. Program will exit.
confluence_5.6.6_postgres_9.5.2 | Invalid file name for use with -Xloggc: Filename can only contain the characters [A-Z][a-z][0-9]-_.%[p|t] but it has been /usr/local/atlassian/confluence/logs/gc-2016-10-18_09:58:48.log
confluence_5.6.6_postgres_9.5.2 | Note %p or %t can only be used once
confluence_5.6.6_postgres_9.5.2 exited with code 1
```

My docker-compose.yml looks like this:

```
confluence:
    container_name: confluence_5.6.6_postgres_9.5.2
    image: cptactionhank/atlassian-confluence:5.6.6
    ports:
        - "8090:8090"
    links:
        - db
        - ldap
db:
    container_name: db_confluence_5.6.6_postgres_9.5.2
    image: postgres:9.5.2
    environment:
        POSTGRES_DB: confluence
        POSTGRES_USER: confluence
        POSTGRES_PASSWORD: confluence
ldap:
    container_name: ldap_confluence_5.6.6_postgres_9.5.2
    image: osixia/openldap:1.1.6
```

When I build your 5.6.6 branch myself and reference it in the docker-compose.yml it works.

```
confluence:
    container_name: confluence_5.6.5_postgres_9.5.2
    build: ../docker-atlassian-confluence
    ...
```

Seems like the image on Docker Hub is broken in some way.
