### ISSUE TITLE
Not able to increase JVM memory.

### ISSUE THREAD

**Issue by cowmix** [cptactionhank/docker-atlassian-confluence#37]
If I change ANY JVM memory setting via **CATALINA_OPTS** I get this:

> Invalid maximum heap size:

**Comment by cptactionhank** [comment]
Please specify your docker command so I can verify because it works for me

**Comment by mccartney** [comment]
I use the following:
> docker run [...] -e "CATALINA_OPTS=-Xmx13g -Xms13g" [...]

and it works.

In practice what happens is that both the default Xmx and the my 13g are supplied and visible in the command line arguments (even in [http://$CONFLUNCE/admin/systeminfo.action](http://$CONFLUNCE/admin/systeminfo.action)), but luckily JVM seems to respect what is mentioned later in the argument chain:

**Comment by mccartney** [comment]
And guessing by the error message:

> Invalid maximum heap size:

you might have a space character after Xmx and before your memory number. Which without Docker is a problem:

```
$ java -Xmx 1g something
Invalid maximum heap size: -Xmx
```

**Comment by cowmix** [comment]
Well, I'm using a docker-compose file, so that might be outside what you guys support:
```

version: '2'
services:
  confluence:
    image: cptactionhank/atlassian-confluence
    container_name: confluence
    volumes:
      - ./apps/data/confluence:/var/atlassian/confluence:z
    ports:
      - "8090:8090"
    environment:
      - CATALINA_OPTS="-Xmx3g -Xms2g"

**Comment by mccartney** [comment]
I am not an expert in Docker Compose. And while I can confirm your file doesn't work. This one does seem to work though (notice no quote signs):

```
version: '2'
services:
  confluence:
    image: cptactionhank/atlassian-confluence
    container_name: confluence
    volumes:
      - ./apps/data/confluence:/var/atlassian/confluence:z
    ports:
      - "8090:8090"
    environment:
      - CATALINA_OPTS=-Xmx3g -Xms2g
```
